### ISSUE TITLE
Release on F-Droid?

### ISSUE THREAD

**Issue by aunyks** [BlueWallet/BlueWallet#233]
Since the wallet is open source and available on Android, I think it'd great for the open source community if it could be released on [F-Droid](https://f-droid.org/). Steps to do so can be [found here](https://f-droid.org/en/tutorials/create-repo/).

**Comment by Overtorment** [comment]
This is a very good idea, thanks for the suggestion! I was thinking about
other platforms except ios & andr, since I hate their monopoly, but there
isn't much alternative. This F-Droid is at least something.

**Comment by PC-Admin** [comment]
Please do, GAPPS dependant wallets are gross, a trend we should avoid.

**Comment by tarbib** [comment]
Hello is this idea still alive? It would be really great for users without Google play services. Thanks !

**Comment by pointbiz** [comment]
As a community I think we need to be prepared for ALL Bitcoin wallets to be banned from the Google Play store. Perhaps at the request of government(s).

There's only 2 Bitcoin wallets on F-Droid but Bluewallet is the current best mobile wallet to recommend to others. It's part of the “freedom stack”.

I pledge 0.1 BTC as a bounty for this issue to be completed. 

See my tweet about it 
https://twitter.com/BtcCuracao/status/1285586746131075072

**Comment by marzzzello** [comment]
Do you guys want to release it on the official repo or on your own repo? Because @aunyks links to the instructions of how to create an own repo.

Since latest release the app now includes google services https://github.com/BlueWallet/BlueWallet/commit/545c8891f6840fbb85e8f0804213cc8a76ef88ed (for push notifications).   
Google services are not allowed in the official F-Droid repo. For the F-Droid build this commit could be patched out.
But the nicer way would be to add a separate build flavor for F-Droid.

**Comment by marcosrdz** [comment]
We use React Native. That flavor would need to parse through all our dependencies and remove any references to that.

**Comment by licaon-kter** [comment]
v5.5.1 builds, but:
* What's up with Hermes? https://github.com/BlueWallet/BlueWallet/issues/1205#issuecomment-662506512
* We need a gradle flavor that excludes InstallReferrer stuff (eg. create some stubs functions instead like https://github.com/iNPUTmice/Conversations/blob/master/src/conversationsFree/java/eu/siacs/conversations/utils/InstallReferrerUtils.java )
* Same for the (not yet tagged) v5.5.2 and [Push functionality](https://github.com/BlueWallet/BlueWallet/commit/545c8891f6840fbb85e8f0804213cc8a76ef88ed)

F-Droid metadata so far _(which pulls the Google libs else it will fail since InstallReferrer needs them)_:
```
License: MIT
SourceCode: https://github.com/BlueWallet/BlueWallet.git
IssueTracker: https://github.com/BlueWallet/BlueWallet.git/issues

AutoName: bluewallet

RepoType: git
Repo: https://github.com/BlueWallet/BlueWallet.git

Builds:
  - versionName: 5.5.1
    versionCode: 1594923516
    commit: v5.5.1
    subdir: android/app
    sudo:
      - sysctl fs.inotify.max_user_watches=524288
      - sysctl -p
      - curl -Lo node.tar.xz https://nodejs.org/dist/v12.18.2/node-v12.18.2-linux-x64.tar.xz
      - echo "b8dc634798ee783482c2ae1755bd7dff09d83fa7bb037cdc370b601d0a5e5cbb node.tar.xz"
        | sha256sum -c -
      - tar xJf node.tar.xz
      - cp -a node-v12.18.2-linux-x64/. /usr/local/
      - npm install -g react-native-cli
    init: npm install
    gradle:
      - yes
    rm:
      - ios
      - node_modules/detox
    prebuild:
      - sed -i -e '/splits/,+7d' -e '/google-services/d' -e '/detox/,+2d' -e 's/enableHermes:\
        false/enableHermes:\ false/' -e 's/versionCode 1/versionCode $$VERCODE$$/'
        build.gradle
      - echo sed -i -e '/installreferrer/,+7d' ../../node_modules/react-native-device-info/android/build.gradle
      - sed -i -e 's/http:/https:/' ../../node_modules/react-native-gesture-handler/android/lib/build.gradle
    scanignore:
      - node_modules/jsc-android
      - node_modules/react-native/android
      - android/build.gradle
      - node_modules/@react-native-community/async-storage/android/build.gradle
      - node_modules/@react-native-community/masked-view/android/build.gradle
      - node_modules/lottie-react-native/build.gradle
      - node_modules/react-native-blue-crypto/android/build.gradle
      - node_modules/react-native-camera/android/build.gradle
      - node_modules/react-native-device-info/android/build.gradle
      - node_modules/react-native-image-picker/android/build.gradle
      - node_modules/react-native-localize/android/build.gradle
      - node_modules/react-native-prompt-android/android/build.gradle
      - node_modules/react-native-safe-area-context/android/build.gradle
      - node_modules/react-native-screens/android/build.gradle
      - node_modules/react-native-secure-key-store/example/android/build.gradle
      - node_modules/react-native-share/android/build.gradle
      - node_modules/react-native-svg/android/build.gradle
      - node_modules/react-native-tcp-socket/android/build.gradle
      - node_modules/react-native-webview/android/build.gradle
      - node_modules/react-native/template/android/build.gradle
    scandelete:
      - node_modules/hermes-engine
      - node_modules/@sentry/cli/sentry-cli
      - node_modules/flow-bin/*/flow*
      - node_modules/jetifier/lib/*.jar
      - node_modules/levelup/node_modules/semver/semver.browser.js.gz
      - node_modules/levelup/node_modules/semver/semver.min.js.gz
      - node_modules/levelup/test/data/testdata.bin
      - node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier
      - node_modules/node-notifier/vendor/notifu/notifu*.exe
      - node_modules/node-notifier/vendor/snoreToast/SnoreToast.exe
      - node_modules/npm-registry/node_modules/semver/semver.browser.js.gz
      - node_modules/npm-registry/node_modules/semver/semver.min.js.gz
      - node_modules/react-native/ReactAndroid/src/main/third-party/java/buck-android-support/buck-android-support.jar

AutoUpdateMode: None
UpdateCheckMode: Tags
```

**Comment by pointbiz** [comment]
> Do you guys want to release it on the official repo or on your own repo? Because @aunyks links to the instructions of how to create an own repo.
> 
> Since latest release the app now includes google services [545c889](https://github.com/BlueWallet/BlueWallet/commit/545c8891f6840fbb85e8f0804213cc8a76ef88ed) (for push notifications).
> Google services are not allowed in the official F-Droid repo. For the F-Droid build this commit could be patched out.
> But the nicer way would be to add a separate build flavor for F-Droid.

I prefer if it's on the official F-Droid repo. I consider that a badge of honor.

**Comment by Overtorment** [comment]
ok how do I help? Im totally not familiar with f-droid

**Comment by licaon-kter** [comment]
@Overtorment read my post above.... Push and Referrer need to be excluded in a flavor.

**Comment by Overtorment** [comment]
I suppose I could maintain a branch without push notifications, that's the easy part.

but `We need a gradle flavor that excludes InstallReferrer stuff ` <-- that I do not understand

**Comment by licaon-kter** [comment]
@Overtorment InstallReferrer is a non-FOSS lib, in that branch without push do exclude this too.

**Comment by folded-pegasus** [comment]
Hi all, I made a packaging request with F-droid here: https://gitlab.com/fdroid/rfp/-/issues/1630

**Comment by fossdd** [comment]
Any progress on InstallReferrer? Or is it already solved?

**Comment by licaon-kter** [comment]
@fossdd That can be removed see updated recipe below.

But react native push thing needs actual dev work ;)

Updated recipe:
```
  - versionName: 6.0.6
    versionCode: 1614602255
    commit: v6.0.6
    subdir: android/app
    sudo:
      - sysctl fs.inotify.max_user_watches=524288
      - sysctl -p
      - curl -Lo node.tar.xz https://nodejs.org/dist/v12.18.2/node-v12.18.2-linux-x64.tar.xz
      - echo "b8dc634798ee783482c2ae1755bd7dff09d83fa7bb037cdc370b601d0a5e5cbb node.tar.xz"
        | sha256sum -c -
      - tar xJf node.tar.xz
      - cp -a node-v12.18.2-linux-x64/. /usr/local/
      - npm install -g react-native-cli
    init: npm install
    gradle:
      - yes
    rm:
      - node_modules/@jest/core/node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier
      - node_modules/@jest/core/node_modules/node-notifier/vendor/notifu/notifu*.exe
      - node_modules/@jest/core/node_modules/node-notifier/vendor/snoreToast/snoretoast*.exe
      - node_modules/@sentry/cli/sentry-cli
      - node_modules/detox-recorder/DetoxRecorder.framework/DetoxRecorder
      - node_modules/detox-recorder/DetoxRecorder.framework/Frameworks/DTXSocketConnection.framework/DTXSocketConnection
      - node_modules/detox-recorder/DetoxRecorderCLI
      - node_modules/detox/Detox-android/com/wix/detox/18.2.2/detox-*.aar
      - node_modules/detox/Detox-android/com/wix/detox/18.2.2/detox-*.jar
      - node_modules/flow-bin/*/flow*
      - node_modules/hermes-engine
      - node_modules/jetifier/lib/*.jar
      - node_modules/levelup/node_modules/semver/semver.*.gz
      - node_modules/levelup/test/data/testdata.bin
      - node_modules/react-native/ReactAndroid/src/main/third-party/java/buck-android-support/buck-android-support.jar
      - node_modules/realm/android/src/main/jniLibs/arm64-v8a/librealmreact.so
      - node_modules/realm/android/src/main/jniLibs/armeabi-v7a/librealmreact.so
      - node_modules/realm/android/src/main/jniLibs/x86/librealmreact.so
      - node_modules/realm/android/src/main/jniLibs/x86_64/librealmreact.so
      - node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier
      - node_modules/node-notifier/vendor/notifu/notifu*.exe
      - node_modules/node-notifier/vendor/snoreToast/snoretoast-x*.exe
    prebuild:
      - sed -i -e '/splits/,+7d' -e '/google-services/d' -e '/detox/,+2d' -e 's/versionCode
        1/versionCode $$VERCODE$$/' build.gradle
      - sed -i -e 's/http:/https:/' ../../node_modules/react-native-gesture-handler/android/lib/build.gradle
      - sed -i -e '/firebase/d' ../../node_modules/react-native-push-notification/android/build.gradle
      - sed -i -e '/com.google.android.play/d' ../../node_modules/react-native-rate/android/build.gradle
      - sed -i -e "/swiperefreshlayout/a implementation(project(':react-native-device-info'))
        { exclude group\x3a 'com.google.firebase'\\ exclude group\x3a 'com.google.android.gms'\\
        exclude group\x3a 'com.android.installreferrer'\\ }" build.gradle
      - sed -i -e '/installReferrerVersion/,+11d' ../../node_modules/react-native-device-info/android/build.gradle
    scanignore:
      - android/build.gradle
      - android/app/build.gradle
      - node_modules/@react-native-async-storage/async-storage/android/build.gradle
      - node_modules/@react-native-community/masked-view/android/build.gradle
      - node_modules/@react-native-community/push-notification-ios/android/build.gradle
      - node_modules/detox/android/build.gradle
      - node_modules/detox/android/detox/detox-publishing.gradle
      - node_modules/jsc-android
      - node_modules/lottie-react-native/build.gradle
      - node_modules/react-native-blue-crypto/android/build.gradle
      - node_modules/react-native-camera/android/build.gradle
      - node_modules/react-native-device-info/android/build.gradle
      - node_modules/react-native-localize/android/build.gradle
      - node_modules/react-native-prompt-android/android/build.gradle
      - node_modules/react-native-rate/android/build.gradle
      - node_modules/react-native-reanimated/android/build.gradle
      - node_modules/react-native-safe-area-context/android/build.gradle
      - node_modules/react-native-screens/android/build.gradle
      - node_modules/react-native-secure-key-store/example/android/build.gradle
      - node_modules/react-native-share/android/build.gradle
      - node_modules/react-native-svg/android/build.gradle
      - node_modules/react-native-tcp-socket/android/build.gradle
      - node_modules/react-native-vector-icons/android/build.gradle
      - node_modules/react-native-webview/android/build.gradle
      - node_modules/react-native-widget-center/android/build.gradle
      - node_modules/react-native/android
      - node_modules/react-native/template/android/build.gradle
      - node_modules/realm/android/build.gradle
```

Which will fail of course:
```

> Task :react-native-push-notification:javaPreCompileRelease

> Task :react-native-push-notification:compileReleaseJavaWithJavac FAILED
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.j
ava:36: error: package com.google.android.gms.tasks does not exist
import com.google.android.gms.tasks.OnCompleteListener;
                                   ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.j
ava:37: error: package com.google.android.gms.tasks does not exist
import com.google.android.gms.tasks.Task;
                                   ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:38: error: package com.google.firebase.iid does not exist
import com.google.firebase.iid.FirebaseInstanceId;
                              ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:39: error: package com.google.firebase.iid does not exist
import com.google.firebase.iid.InstanceIdResult;
                              ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:40: error: package com.google.firebase.messaging does not exist
import com.google.firebase.messaging.FirebaseMessaging;
                                    ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java:3: error: package com.google.firebase.messaging does not exist
import com.google.firebase.messaging.FirebaseMessagingService;
                                    ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java:4: error: package com.google.firebase.messaging does not exist
import com.google.firebase.messaging.RemoteMessage;
                                    ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java:31: error: cannot find symbol
    private FirebaseMessagingService mFirebaseMessagingService;
            ^
  symbol:   class FirebaseMessagingService
  location: class RNReceivedMessageHandler
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java:33: error: cannot find symbol
    public RNReceivedMessageHandler(@NonNull FirebaseMessagingService service) {
                                             ^
  symbol:   class FirebaseMessagingService
  location: class RNReceivedMessageHandler
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java:37: error: cannot find symbol
    public void handleReceivedMessage(RemoteMessage message) {
                                      ^
  symbol:   class RemoteMessage
  location: class RNReceivedMessageHandler
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java:3: error: package com.google.firebase.messaging does not exist
import com.google.firebase.messaging.FirebaseMessagingService;
                                    ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java:4: error: package com.google.firebase.messaging does not exist
import com.google.firebase.messaging.RemoteMessage;
                                    ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java:19: error: cannot find symbol
public class RNPushNotificationListenerService extends FirebaseMessagingService {
                                                       ^
  symbol: class FirebaseMessagingService
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java:22: error: cannot find symbol
    private FirebaseMessagingService mFirebaseServiceDelegate;
            ^
  symbol:   class FirebaseMessagingService
  location: class RNPushNotificationListenerService
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java:29: error: cannot find symbol
    public RNPushNotificationListenerService(FirebaseMessagingService delegate) {
                                             ^
  symbol:   class FirebaseMessagingService
  location: class RNPushNotificationListenerService
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java:76: error: cannot find symbol
    public void onMessageReceived(RemoteMessage message) {
                                  ^
  symbol:   class RemoteMessage
  location: class RNPushNotificationListenerService
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:124: error: cannot find symbol
              .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                                         ^
  symbol:   class OnCompleteListener
  location: class RNPushNotification
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:124: error: cannot find symbol
              .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                                                            ^
  symbol:   class InstanceIdResult
  location: class RNPushNotification
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:123: error: cannot find symbol
      FirebaseInstanceId.getInstance().getInstanceId()
      ^
  symbol:   variable FirebaseInstanceId
  location: class RNPushNotification
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:141: error: cannot find symbol
        FirebaseMessaging.getInstance().subscribeToTopic(topic);
        ^
  symbol:   variable FirebaseMessaging
  location: class RNPushNotification
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:146: error: cannot find symbol
        FirebaseMessaging.getInstance().unsubscribeFromTopic(topic);
        ^
  symbol:   variable FirebaseMessaging
  location: class RNPushNotification
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:270: error: cannot find symbol
                  FirebaseInstanceId.getInstance().deleteInstanceId();
                  ^
  symbol: variable FirebaseInstanceId
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java:39: error: package RemoteMessage does not exist
        RemoteMessage.Notification remoteNotification = message.getNotification();
                     ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java:35: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java:38: error: cannot find symbol
        final FirebaseMessagingService serviceRef = (this.mFirebaseServiceDelegate == null) ? this : this.mFirebaseServiceDelegate;
              ^
  symbol:   class FirebaseMessagingService
  location: class RNPushNotificationListenerService
/home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java:75: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /home/vagrant/build/io.bluewallet.bluewallet/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
26 errors

> Task :react-native-prompt-android:bundleLibCompileToJarRelease
> Task :react-native-quick-actions:javaPreCompileRelease

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-push-notification:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
